name: Publish
on:
  push:
    branches:
      - main
      - add-arbitrary-options

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dylanvann/publish-github-action@v1.1.49
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
